{{- $chartName := include "external-to-osm-tag-mapping.name" . -}}
{{- $tracingUrl := include "external-to-osm-tag-mapping.tracingUrl" . -}}
{{- $metricsUrl := include "external-to-osm-tag-mapping.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{- if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{- end }}
  {{- if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{- end }}
  SCHEMA_FILE_PATH: /mnt/schemas/schema.json
  DB_CONNECTION_STRING: redis://user:password@hostname:6379/0?maxRetriesPerRequest=1&lazyConnect=false
{{- end }}
