{{- $chartName := include "external-to-osm-tag-mapping.name" . -}}
{{- $tracingUrl := include "external-to-osm-tag-mapping.tracingUrl" . -}}
{{- $metricsUrl := include "external-to-osm-tag-mapping.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{- if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  TELEMETRY_TRACING_RATIO: {{ .Values.env.tracing.ratio | quote }}
  {{- end }}
  {{- if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{- end }}
  SCHEMA_FILE_PATH: /mnt/schemas/schema.json
  {{- with .Values.dbConfig }}
  DB_HOST: {{ .host | quote }}
  DB_PORT: {{ .port | quote }}
  DB_INDEX: {{ .index | quote }}
  DB_MAX_RETRIES_PER_REQUEST: {{ .maxRetriesPerRequest | quote }}
  {{- end }}
  {{- if .Values.env.hashKey.enabled }}
  APP_HASH_KEY_ENABLED: 'true'
  APP_HASH_KEY: {{ .Values.env.hashKey.value | quote }}
  {{- end }}
  npm_config_cache: /tmp/
{{- end }}
