{{- $chartName := include "external-to-osm-tag-mapping.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-schema-configmap
data:
  schema.json: |-
{{ .Values.schema | indent 4 }} 
{{- end }}