{{- $releaseName := .Release.Name -}}
{{- $chartName := include "external-to-osm-tag-mapping.name" . -}}
{{- if and .Values.enabled .Values.dbConfig (or .Values.dbConfig.username .Values.dbConfig.password ) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "external-to-osm-tag-mapping.environment" . }}
    release: {{ $releaseName }}
    {{- include "external-to-osm-tag-mapping.labels" . | nindent 4 }}
data:
  {{- if .Values.dbConfig.username }}
  DB_USERNAME: {{ .Values.dbConfig.username | b64enc }}
  {{- end }}
  {{- if .Values.dbConfig.password }}
  DB_PASSWORD: {{ .Values.dbConfig.password | b64enc }}
  {{- end }}
{{- end }}