{{- $releaseName := .Release.Name -}}
{{- $chartName := include "external-to-osm-tag-mapping.name" . -}}
{{- $cloudProviderFlavor := include "external-to-osm-tag-mapping.cloudProviderFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "external-to-osm-tag-mapping.environment" . }}
    release: {{ $releaseName }}
    {{- include "external-to-osm-tag-mapping.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "external-to-osm-tag-mapping.selectorLabels" . | nindent 4 }}
{{- end }}
