global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
initialDelaySeconds: 60
replicaCount: 1

schema: |-
  [
    {
      "name": "system1",
      "createdAt": "2021-07-14T11:19:58Z",
      "updatedAt": "2021-07-14T11:19:58Z",
      "addSchemaPrefix": false,
      "enableExternalFetch": "yes",
      "domainFieldsListKey": "DISCRETE_ATTRIBUTES",
      "explodeKeys": ["explode1", "explode2"]
    },
    {
      "name": "system2",
      "createdAt": "2021-07-14T11:19:58Z",
      "updatedAt": "2021-07-14T11:19:58Z",
      "addSchemaPrefix": true,
      "enableExternalFetch": "no"
    }
  ]

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  flavor: openshift

image:
  repository: external-to-osm-tag-mapping
  tag: 'latest'

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

dbConfig:
  host: redis
  port: 6379
  index: 0
  username: '' #pass '' (empty string) when username is not needed
  password: '' #pass '' (empty string) when password is not needed
  maxRetriesPerRequest: 0

app:
  enabled: false
  hashKey: system1

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  path: /
