global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
initialDelaySeconds: 60
replicaCount: 1

schema: |
  [
    {
      "name": "system1",
      "createdAt": "2021-07-14T11:19:58Z",
      "updatedAt": "2021-07-14T11:19:58Z"
    },
    {
      "name": "system2",
      "createdAt": "2021-07-14T11:19:58Z",
      "updatedAt": "2021-07-14T11:19:58Z"
    }
  ]

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  flavor: openshift

image:
  repository: external-to-osm-tag-mapping
  tag: 'latest'

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  path: /
