openapi: 3.0.1
info:
  title: external-to-osm-tag-mapping
  description: mapping  external tags to osm tags - json format
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /schemas/{name}/map:
    post:
      tags: 
        - schemas
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: the service name
      summary: osm tags mapping
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              { externalKey1: externalValue1, externalKey2: externalValue2 }
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                {
                  defaultOsmKey: defaultOsmValue,
                  defaultOsmKey1: defaultOsmValue1,
                  osmKey: externalValue,
                  osmKey1: externalValue1,
                }
        400:
          $ref: '#/components/responses/BadRequest'
        5XX:
          $ref: '#/components/responses/InternalError'
  /schemas/{name}:
    get:
      tags: 
        - schemas
      summary: get schema by service name
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: the service name
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                example: { externalKey1: osmKey1, externalKey2: osmKey2 }
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        5XX:
          $ref: '#/components/responses/InternalError'
  /schemas:
    get:
      tags: 
        - schemas
      summary: get all existing schemas
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  type: object
              example:
                [
                  {
                    system1: { externalKey1: osmKey1, externalKey2: osmKey2 },
                  },
                  {
                    system2: { externalKey1: osmKey1, externalKey2: osmKey2 },
                  },
                ]
        400:
          $ref: '#/components/responses/BadRequest'
        5XX:
          $ref: '#/components/responses/InternalError'
components:
  responses:
    BadRequest:
      description: bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example: { code: 400, message: bad request }
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example: { code: 404, message: resource not found }
    InternalError:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example: { code: 500, message: internal server error }
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message
