name: pull_request

on: [pull_request]

jobs:
  eslint:
    name: Run eslint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['24.x']

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          prettier: true
          eslint_extensions: ts

      - name: OpenAPI Lint Checks
        uses: nwestfall/openapi-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./openapi3.yaml

  tests:
    name: Run Tests (Node ${{ matrix.node }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['24']
      fail-fast: false

    container: node:${{ matrix.node }}

    services:
      redis:
        image: redis:7.2.1
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

      - uses: actions/upload-artifact@v5
        with:
          name: Test Reporters - Node v${{ matrix.node }}
          path: reports/**

  build_image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: build Docker image
        run: docker build -t test-build:latest .
